#include <iostream>
#include <fstream>
#include <string>

int main() {
    std::ofstream outfile("index.html");

    // Write HTML content
    outfile << "<html>\n<body>\n";
    outfile << "<h1>Hello from my C++ program!</h1>\n";
    outfile << "<p>This content was generated by a C++ executable.</p>\n";
    outfile << "</body>\n</html>";

    outfile.close();
    return 0;
}
